### ISSUE TITLE
Rellenar el formulario para el milestone 2

### ISSUE THREAD

**Issue by alejandrohall** [Proyecto-EGC-G1/Autenticacion-EGC-G1#13]
Hay que rellenar el formulario a entregar el día para desarrollar el milestone 2

**Comment by alejandrohall** [comment]
Ya está creado el formulario.

**Comment by tomasruan** [comment]
1.1) ¿En qué situación está el proyecto? ¿Cuáles son los hitos siguientes?

El proyecto se encuentra actualmente en un estado dotado de total funcionalidad, pues están definidas y desarrolladas todas las funcionalidades propuestas. Se ha realizado el mapeo de los objetos de la base de datos al ORM, se han diseñado y desarrollado los endpoints necesarios para comprobar las cookies, cerrar sesión, asignar roles. Se ha creado el método para comprobar las contraseñas, además de haberse creado también el formulario y se ha dotado de funcionalidad al login. 

Los hitos siguientes son los de integrar nuestro subsistema junto con el resto de subsistemas, implementar la gestión de incidencias de manera automática y gestionar la construcción, el testing y el despliegue con el uso de integración continua.


2) Explique cual va a ser el/los cambios que va a haber en su proyecto y cual/es ha implementado ya.

Una reimplementación del login en Python, y se añade también la funcionalidad para que otros grupos, mediante API REST, puedan comprobar cookies, asignar roles y cerrar sesión de un usuario.

3 Explique (y dibuje si es necesario) el proceso de gestión de código y gestión de incidencias.

EL código fuente y las incidencias han sido gestionadas de la siguiente manera:

Disponemos de una rama master, y varias ramas secundarias (una para cada miembro del equipo). Cada miembro del equipo ha sido asignado con un número determinado de Issues (repartidas por el coordinador del equipo). Dichas Issues corresponden con distintas tareas necesarias para la realización del proyecto. 
Cada miembro del equipo realiza sus tareas correspondientes, realizando commits a su rama cuándo realice cambios lógicos. Tras estos commits y los push a la rama en cuestión, el coordinador del equipo revisa los cambios para hace un futuro merge a la rama develop en caso de que los cambios realizados sean correctos.  Tras la realización de la tarea a completar se mueve la tarea a “Need revision” en el Kanban, que contiene las distintas Issues asignadas a los distintos miembros del equipo. Tras esto, el coordinador del equipo revisa dichas Issues y si los cambios son correctos, procede a cerrar las Issues y a hacer merge en la rama develop con los cambios realizados. Una vez se haga merge a la rama master cuando estén todas las tareas completadas, se creará una tag de github para que se pueda navegar entre el contenido entregado de cada milestone.
