### ISSUE TITLE
Crear el método para comprobar contraseñas

### ISSUE THREAD

**Issue by alejandrohall** [Proyecto-EGC-G1/Autenticacion-EGC-G1#14]
Con la investigación hecha en #4 hay que crear un método que dado un string (contraseña) y un hash, compruebe si son iguales o no.

**Comment by frasanvel** [comment]
Comento los avances. He comenzado la implementación usando la librería citada en #4: `Python-phpass`, pero debido a múltiples problemas de compabilidad con el código (y a su vez con las librerías que está usando) he tenido que investigar otras alternativas.

Finalmente he usado la librería `passlib` que tenía diversos métodos y clases relacionadas con seguridad, entre ellos se incluye phpass. Mediante el método `.hash(textoPlano)` se puede obtener un hash de una contraseña en texto plano. A su vez, usando `.verify(textoPlano, hash)`, devuelve un booleano indicando si la contraseña en texto plano corresponde al hash o no.

**Comment by alejandrohall** [comment]
Perfecto, integrado con el código.
