### ISSUE TITLE
Crear espacio en la Wiki

### ISSUE THREAD

**Issue by alejandrohall** [Proyecto-EGC-G1/Autenticacion-EGC-G1#20]
Tenemos que añadir un espacio en la wiki con la siguiente información:

* Miembros (Nombre de los miembros)
* Repositorio (Enlace al repositorio)
* Opera (Enlace a Opera)
* Entorno (Tecnologías que estamos usando)
* Endpoints (Toda la información de los endpoints, incluido el tuyo de Logout, cuando lo mejores con la issue #18)

**Comment by Garbancito** [comment]
Ya se puede acceder a toda la información de nuestro grupo a partir del siguiente enlace:
https://1984.lsi.us.es/wiki-egc/index.php/Autenticaci%C3%B3n_-_17_18_-_G1

**Comment by alejandrohall** [comment]
Perfecto
