### ISSUE TITLE
Formulario M3

### ISSUE THREAD

**Issue by alejandrohall** [Proyecto-EGC-G1/Autenticacion-EGC-G1#22]
Hay que crear el formulario del milestone 3 que se encuentra en [este enlace](https://1984.lsi.us.es/wiki-egc/index.php/Archivo:M3_17_18.pdf)

**Comment by caolin333** [comment]
1 - Haga un informe del estado del proyecto y las dificultades encontradas hasta este hito

El proyecto ha seguido desarrollándose ya que hemos finalizado los issues propuestos. Se ha realizado la construcción de la imagen de Docker, se ha cambiado el endpoint de cerrar sesión y comprobación de cookies en relación al nuevo modelo y el modelo para añadir los cambios relacionados, se ha hecho la validación del login en la parte del servidor, se ha modificado el login con la cookie en SHA1 y los scripts del populate, se ha creado un script para la generación de imagen de Docker, se ha creado el espacio en la wiki, se ha investigado el suite de test, se ha configurado la integración continua y se ha hecho el testing de las funcionalidades que tenemos.

2 - ¿Tiene un proceso definido para la gestión de incidencias?-¿Implementa ese proceso en la práctica?¿Tiene un proceso definido para la gestión de código?¿Implementa ese proceso en la práctica?¿Tiene algún mecanismo automático de conexión entre las incidencias y la gestión del código?

Disponemos de una rama master, y varias ramas secundarias (una para cada miembro del equipo). Cada miembro del equipo ha sido asignado con un número determinado de Issues (repartidas por el coordinador del equipo). Dichas Issues corresponden con distintas tareas necesarias para la realización del proyecto.
Cada miembro del equipo realiza sus tareas correspondientes, realizando commits a su rama cuándo realice cambios lógicos. Tras estos commits y los push a la rama en cuestión, el coordinador del equipo revisa los cambios para hace un futuro merge a la rama develop en caso de que los cambios realizados sean correctos.  Tras la realización de la tarea a completar se mueve la tarea a “Need revision” en el Kanban, que contiene las distintas Issues asignadas a los distintos miembros del equipo. Tras esto, el coordinador del equipo revisa dichas Issues y si los cambios son correctos, procede a cerrar las Issues y a hacer merge en la rama develop con los cambios realizados. Una vez se haga merge a la rama master cuando estén todas las tareas completadas, se creará una tag de github para que se pueda navegar entre el contenido entregado de cada milestone.

¿Tiene mecanismos de automatización de la construcción (build)?
Si, cuando se hace un push a develop o master, la integración continua se trae el repositorio, e instala las dependencias

¿Tiene mecanismos de automatización para la ejecución de pruebas?
Si, una vez instaladas las dependencias se ejecutan los tests 

¿Tiene mecanismos de automatización de la integración?
No usamos ese flujo (a través de pull request) pero lo tenemos configurado y es funcional.

¿Tiene mecanismos de automatización de la entrega y despliegue del sistema?
Si, cuando los tests pasan satisfactoriamente, se genera la imagen de docker y se sube al dockerhub. 
Aparte, hemos hecho una mini API para ayudarlos que se encarga de, una vez que un grupo ha terminado de generar la imagen de docker y subirla a docker hub, se le pasa a ese endpoint el nombre del grupo y docker se encarga de tirar el contenedor específico y levantarlo con la imagen nueva generada anteriormente.

¿Está desplegado el sistema de manera aislada?
Si, cuando los tests pasan satisfactoriamente, se genera la imagen de docker y se sube al dockerhub.

¿Está integrado su subsistema con el resto de subsistemas?
Todavia no.

**Comment by alejandrohall** [comment]
Por mi está perfecto
