### ISSUE TITLE
Investigar suite de test

### ISSUE THREAD

**Issue by alejandrohall** [Proyecto-EGC-G1/Autenticacion-EGC-G1#23]
Investigar suite de test para testear los métodos y poder ejecutar algo en la integración continua.

**Comment by manuelgomezsuarez** [comment]
Para testear los metodos de la API usaremos el framework Pytest con el plugin para Flask Pytest-flask´s.
Necesitamos por tanto instalar Pytest y Pytest-flask´s mediante el comando pip.

Para comenzar con el testing, solo necesitamos crear la clase conftest.py en la cual configuramos pytest y ya podemos empezar a crear tests.
Los tests creados estarán en la carpeta "tests" del proyecto, y serán implementados en el fichero "test_aplicacion".

Una vez los tests están implementados, basta con abrir la terminal en la carpeta tests y ejecutar el comando "pytest" para comprobar el resultado.

Documentación Pytest: [https://pytest-flask.readthedocs.io/en/latest/](url)
Documentación Pytest-flask´s: [https://docs.pytest.org/en/latest/](url)

**Comment by manuelgomezsuarez** [comment]
¿@alejandrohall podrías incluir estas dos herramientas al requirements.txt para facilitar su instalación al resto del grupo?

**Comment by alejandrohall** [comment]
Por supuesto, las añado en un momento

**Comment by alejandrohall** [comment]
Ya está añadida la dependecia e integrada en develop. Buen trabajo con las suite de prueba.

**Comment by Garbancito** [comment]
Escribir por consola lo siguiente en una sola linea en lugar de "pytest":

MARIADB_PORT=3306 MARIADB_HOST=127.0.0.1 MARIADB_USER=root MARIADB_PASSWORD=root123 pytest
