### ISSUE TITLE
Hacer testing de la asignación de roles

### ISSUE THREAD

**Issue by caolin333** [Proyecto-EGC-G1/Autenticacion-EGC-G1#32]
Con el objetivo de aligerar el trabajo de la issue #24 Realizar el test del método de cambiar rol.

**Comment by tomasruan** [comment]
He creado el test de comprobación de User incorrecto. He dejado un commit en la issue Ref #24 
Miratelo. (Añade test de comprobación de User incorrecto. Ref #24) Es el nombre del commit.

**Comment by alejandrohall** [comment]
Integrada en develop
