### ISSUE TITLE
Cambiar el endpoint de cerrar sesion en relación al nuevo modelo

### ISSUE THREAD

**Issue by Garbancito** [Proyecto-EGC-G1/Autenticacion-EGC-G1#33]
Realizar los cambios oportunos para que el borrado de cookies se realice con tipo String en lugar de Integer.

**Comment by alejandrohall** [comment]
¿Dónde están los commits que referencian esta issue? ¿Por qué está en need revision si no tiene commits?

**Comment by alejandrohall** [comment]
Perfecto, integrado en develop.
