### ISSUE TITLE
Diseñar endpoint para cerrar sesión

### ISSUE THREAD

**Issue by Garbancito** [Proyecto-EGC-G1/Autenticacion-EGC-G1#35]
**Url de entrada para cerrar sesion:**
/logout

**Verbos:**
Petición GET

**Salida:**
Se busca la cookie de la sesión  y en caso de obtenerla, se procede a borrar la cookie de la base de datos. Después se redirige a /login

**Comment by alejandrohall** [comment]
Está bien
