### ISSUE TITLE
Investigar cómo hashea las contraseñas Wordpress

### ISSUE THREAD

**Issue by alejandrohall** [Proyecto-EGC-G1/Autenticacion-EGC-G1#4]
Los usuarios registrados en el Wordpress que acepten ser añadidos al sistema de votación se copiarán desde la tabla de Wordpress a la tabla de votaciones. Para hacer el login tendremos que investigar cómo hashea las contraseñas Wordpress para poder comprobar el usuario y la contraseña.

**Comment by javiersantos** [comment]
Basicamente la lógica para crear el hash de la contraseña se hace en `wp-includes/class-phpass.php` (algo que no voy a entrar en detalles porque sería un locura de entender).

Desde `wp-includes/pluggable.php` podemos llamar a la función `wp_hash_password(string)` para obtener el hash del texto plano dado como parámetro.

Voy a realizar un sencillo script que haga uso de esos métodos.

**Comment by alejandrohall** [comment]
@javiersantos pero cómo vas a llamar a una función de PHP desde Python?

**Comment by javiersantos** [comment]
Por lo que veo existen diversas manera de ejecutar código PHP en Python:
* https://stackoverflow.com/questions/8984287/execute-php-code-in-python
* https://github.com/leekchan/phpy

Si funciona solo necesitariamos importar el archivo `class-phpass.php` y crear una función para comprobar hash y contraseña en texto plano. Si no funciona ya vería otras alternativas.

**Comment by frasanvel** [comment]
Por lo que veo existen diversas manera de ejecutar código PHP en Python:
* https://stackoverflow.com/questions/8984287/execute-php-code-in-python
* https://github.com/leekchan/phpy

Si funciona solo necesitariamos importar el archivo `class-phpass.php` y crear una función para comprobar hash y contraseña en texto plano. Si no funciona ya vería otras alternativas.

**Comment by alejandrohall** [comment]
Todas se basan en que tienes acceso al fichero en cuestión, recuerda que la aplicación se está ejecutando dentro de un Docker y no se tiene acceso ni siquiera al código de la aplicación de votación de los compañeros, así que imaginate al del proyecto de Wordpress.

**Comment by alejandrohall** [comment]
@frasanvel 

Puedes intentar tirar de aquí: https://github.com/exavolt/python-phpass

Parece ser que es un port de Phpass, que es lo que utiliza WP, en Python. Pero hay que investigar si es Python 2 o 3, y si fuera 2, se puede portear al 3, que no debe ser muy complicado

**Comment by alejandrohall** [comment]
Se ha usado la librería arriba propuesta para la implementación.
