### ISSUE TITLE
Investigar cómo distinguir ramas en CI

### ISSUE THREAD

**Issue by frasanvel** [Proyecto-EGC-G1/Autenticacion-EGC-G1#40]
Actualmente el archivo `build_and_upload_docker_image.sh` se ejecuta tanto en `master` como en `develop`. Hay que investigar para hacer que solo se ejecute en `master`, pero que la integración continúa siga funcionando en ambos. Para ello seguramente sea necesario usar las variables de entorno de Travis. Ref #38.

**Comment by frasanvel** [comment]
Travis crea una variable de entorno `$TRAVIS_BRANCH` con el nombre de la rama actual. Podemos usar dicha variable dentro del apartado `script` del archivo `.travis.yml` de la siguiente forma:

```yml
script:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then bash build_and_upload_docker_image.sh; fi
```

O directamente en el archivo bash que se vaya a ejecutar.

**Comment by alejandrohall** [comment]
Perfecto!
