### ISSUE TITLE
Redactar documento: Gestión del cambio, incidencias y depuración

### ISSUE THREAD

**Issue by caolin333** [Proyecto-EGC-G1/Autenticacion-EGC-G1#49]
¿qué mecanismos de depuración se usan? ¿cómo se gestionan los cambios? ¿qué procesos? ¿qué roles? ¿qué estados se manejan? ¿qué políticas para descartar, fomentar o retardar un cambio?.
La gestión de incidencias debería contener explícitamente dos partes. Una de cómo
se han gestionado la incidencias internas y otro el cómo se han gestionado y se
ofrece protocolo para gestionar las incidencias externas tanto las recibidas como
las que se reporten a otros subsistemas. Cuando una incidencia esté relacionada
con un commit, señalar el commit dentro de la propia incidencia.

**Comment by caolin333** [comment]
Para los mecanismos de depuración usamos los que nos ofrece PyCharm, que es el IDE que utilizamos para el proyecto.
Disponemos de una rama master, y varias ramas secundarias (una para cada miembro del equipo). Cada miembro del equipo ha sido asignado con un número determinado de Issues (repartidas por el coordinador del equipo). Dichas Issues corresponden con distintas tareas necesarias para la realización del proyecto.
Cada miembro del equipo realiza sus tareas correspondientes, realizando commits a su rama cuándo realice cambios lógicos. Tras estos commits y los push a la rama en cuestión, el coordinador del equipo revisa los cambios para hacer un futuro merge a la rama develop en caso de que los cambios realizados sean correctos. Tras la realización de la tarea a completar se mueve la tarea a “Need revision” en el Kanban, que contiene las distintas Issues asignadas a los distintos miembros del equipo. Tras esto, el coordinador del equipo revisa dichas Issues y si los cambios son correctos, procede a cerrar las Issues y a hacer merge en la rama develop con los cambios realizados. Una vez se haga merge a la rama master cuando estén todas las tareas completadas, se creará un tag de github para que se pueda navegar entre el contenido entregado de cada milestone.
Las políticas pueden ser tiempo, importancia, si es fundamental y dificultad. Según el valor de estas variables se considerará debidamente el cambio.

**Comment by alejandrohall** [comment]
Cuidado, tienes que respetar el formato que dijo el profesor en clases, se está mezclando todo:

- Debe quedar clara, en cada bloque, la diferencia entre:
  - el proceso abstracto de gestión definido
  - la herramienta que da soporte e implementa dicho proceso y cómo se usa dicha herramienta
la posible descripción de la instalación de dicha herramienta si es que fuera relevante y necesario. En muchos casos podría ser más práctico poner un vídeo y poner un enlace al mismo describiendo estos pasos.  (Opcional)
  - evidencias de que ha seguido el proceso descrito con las herramientas descritas en su propio proyecto
  - lecciones aprendidas si las hubiera. En este apartado se pueden poner reflexiones y lecciones aprendidas. Se hizo algo de una forma y se ha visto que, tal vez, hubiera sido mejor hacerlo de otro modo.

**Comment by caolin333** [comment]
Para el manejo de las incidencias, usaremos las issues de Github junto con los proyectos de Github, lo que nos dará una combinación que nos permita saber todas nuestras incidencias y el estado de ella en un tablero Kanban.

Disponemos de una rama master, y varias ramas secundarias (una para cada miembro del equipo). Cada miembro del equipo ha sido asignado con un número determinado de Issues (repartidas por el coordinador del equipo). Dichas Issues corresponden con distintas tareas necesarias para la realización del proyecto.

Cada miembro del equipo realiza sus tareas correspondientes, realizando commits a su rama cuándo realice cambios lógicos. Tras estos commits y los push a la rama en cuestión, el coordinador del equipo revisa los cambios para hacer un futuro merge a la rama develop en caso de que los cambios realizados sean correctos. Tras la realización de la tarea a completar se mueve la tarea a “Need revision” en el Kanban, que contiene las distintas Issues asignadas a los distintos miembros del equipo. Tras esto, el coordinador del equipo revisa dichas Issues y si los cambios son correctos, procede a cerrar las Issues y a hacer merge en la rama develop con los cambios realizados. Una vez se haga merge a la rama master cuando estén todas las tareas completadas, se creará un tag de github para que se pueda navegar entre el contenido entregado de cada milestone.

Para los mecanismos de depuración usamos los que nos ofrece PyCharm, que es el IDE que utilizamos para el proyecto.

Evidencias: 

Todas las ramas creadas para cada miembro
![ramas](https://user-images.githubusercontent.com/22836491/34908188-3d9e73e2-f88c-11e7-96cf-e04336716542.PNG)

Ejemplo de Issues
![issues](https://user-images.githubusercontent.com/22836491/34908186-3d5d222a-f88c-11e7-8328-9ebc434c9b30.PNG)

Ejemplo de Issue cerrada con commits e integrada en develop
![issue cerrada con sus commits y todo](https://user-images.githubusercontent.com/22836491/34908185-3d3f5074-f88c-11e7-92ca-006dd1b849f9.PNG)

Ejemplo de estado de Kanban
![kanban](https://user-images.githubusercontent.com/22836491/34908187-3d7b22ca-f88c-11e7-8de0-eab1f5b0951e.PNG)


Lecciones aprendidas: Como la mayoría del grupo no había trabajado mucho con GitHub, se creó esta organización de issues, ramas y Kanban para que fuese mas fácil entenderse entre todos y tener claro en que trabajaba quien. Durante el transcurso del proyecto no ha sido necesario cambiarlo y eso es una marca de que estaba bien organizado. No veo de que manera se podría haberse organizado con nuestra experiencia en GitHub.

**Comment by alejandrohall** [comment]
Raúl, tienes que separar el proceso de la herramienta, estas mezclando el proceso con la herramienta
