### ISSUE TITLE
Diseñar endpoint para asignar roles

### ISSUE THREAD

**Issue by alejandrohall** [Proyecto-EGC-G1/Autenticacion-EGC-G1#5]
Uno de los endpoints que necesitamos crear será para que otros subsistemas puedan asignar roles, para ello tenemos que diseñar el endpoint, hay que diseñar estas 4 cosas:

* Nombre del endpoint
* Verbos del endpoint
* Formato del json de entrada
* Formato del json de salida

**Comment by caolin333** [comment]
Url de entrada para comprobar cookies:
/assignRole/{id_usuario}/{nuevo role}
Verbos:
Petición GET
Salida → Json con la siguiente información:
codigo:
0 → La Id de usuario no existe en la base de datos
1 → El role ha sido cambiado

status:
para Código 0 → "Id de usuario incorrecta, no existe en la base de datos"
para Código 1 → "Role cambiado"

usuario:
para código 0 → null
para código 1 → json con los datos de la cuenta de usuario asociado al ID.

Ejemplo Salida ID Válida:

{
    "assignRole": {
         "codigo": 1, 
         "status": "Role cambiado", 
    "usuario": {
         "email": "sdsd", 
         "id": 3, 
         "password": "sds", 
         "role_id": 1, 
         "username": "lba"
    }
  }
}
Ejemplo Salida ID Incorrecta:

{
  "assignRole": {
    "codigo": 0, 
    "status": "Id de usuario incorrecta, no existe en la base de datos", 
    "usuario": null
  }
}

**Comment by alejandrohall** [comment]
El diseño está mal. Primero, los verbos GET no pueden generar un cambio en el sistema por el principio de seguridad de REST. Para eso existen otro métodos. Segundo, en las urls se ponen nombres, no acciones, que junto con el verbo que tienes que utilizar (que funciona distinto a GET), hace que la URL no sea correcta. Un ej de url correcta sería _/user/{user_id}/role_.

**Comment by caolin333** [comment]
Url de entrada para asignar roles:
/users/<int:user_id>
Verbos:
Petición PUT
Entrada → Json con el nuevo role.
Salida → Json con la siguiente información:
codigo:
0 → La Id de usuario no existe en la base de datos
1 → El role ha sido cambiado

status:
para Código 0 → "Id de usuario incorrecta, no existe en la base de datos"
para Código 1 → "Role cambiado"

usuario:
para código 0 → null
para código 1 → json con los datos de la cuenta de usuario asociado al ID.

Ejemplo Salida ID Válida:

{
    "assignRole": {
         "codigo": 1, 
         "status": "Role cambiado", 
    "usuario": {
         "email": "sdsd", 
         "id": 3, 
         "password": "sds", 
         "role_id": 1, 
         "username": "lba"
    }
  }
}
Ejemplo Salida ID Incorrecta:

{
  "assignRole": {
    "codigo": 0, 
    "status": "Id de usuario incorrecta, no existe en la base de datos", 
    "usuario": null
  }
}

**Comment by alejandrohall** [comment]
Perfecto, todo ok.
