### ISSUE TITLE
Diseñar endpoint para comprobar cookies

### ISSUE THREAD

**Issue by alejandrohall** [Proyecto-EGC-G1/Autenticacion-EGC-G1#6]
Uno de los endpoints que necesitamos crear será para que otros subsistemas puedan comprobar las cookies, para ello tenemos que diseñar el endpoint, hay que diseñar estas 4 cosas:

* Nombre del endpoint
* Verbos del endpoint
* Formato del json de entrada
* Formato del json de salida

**Comment by manuelgomezsuarez** [comment]
**Url de entrada para comprobar cookies:**
/cookie/{number_id}
**Verbos:**
Petición GET
**Salida** →  Json con la siguiente información:
**codigo:**
-1 →  si existe en la base de datos pero ha ocurrido un error al obtener el usuario o no    
            existe usuario asociado.
0 →  Si no existe la cookie en la base de datos
1 → La cookie existe en la base de datos y tiene un usuario asociado

**status:** 
para Código -1 → “Coincidencia de cookie encontrada en la base de datos pero no es posible obtener el User Account”
para Código 0 → "Cookie Incorrecta, no existe en la base de datos"
para Código 1 → "Cookie válida y existente en la base de datos"

**usuario:**
para código -1 ó 0 → null
para código 1 → json con los datos de la cuenta de usuario asociado a la cookie.

**Ejemplo Salida Cookie Válida:**
{
  "checkCookie": {
    "codigo": 1, 
    "status": "Cookie valida y existente en la base de datos", 
    "usuario": {
      "email": "imosciski@example.com", 
      "id": 3, 
      "password": "77d6ab52742226b77d651f0e12fa22ff6adda3b9", 
      "role_id": 2, 
      "username": "rickey.nolan"
    }
  }
}

**Ejemplo Salida Cookie Incorrecta:**
{
  "checkCookie": {
    "codigo": 0, 
    "status": "Cookie Incorrecta, no existe en la base de datos", 
    "usuario": null
  }
}

**Comment by alejandrohall** [comment]
Yo creo que no hay ningún caso en el que se vaya a usar el código de salida -1. Puedes quitarlo de la implementación?

**Comment by manuelgomezsuarez** [comment]
Si, tienes razón esa situación no es posible. Ya está corregido en el código.

**Comment by alejandrohall** [comment]
Perfecto, cierro esto!
